### ISSUE TITLE
文字入力ができずに落ちる

### ISSUE THREAD

**Issue by Cj-bc** [pirka-ai/pirka-ai#1]
先ずは制作お疲れ様です！！

問題
====

試してみたところ、文字を入力した時に何故か文字が反映されずに落ちてしまいます。
添付したGifの状態で、1度目日本語を打ちその後アルファベットを打っているのですがどちらも反映されませんでした。
![pirka-ai_fail_201901262223](https://user-images.githubusercontent.com/16875061/51787966-5fb7e900-21bb-11e9-9dfb-78418495252f.gif)

環境:
===

```
<X_X>:drcs.vim$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.3
BuildVersion:   18D42
<X_X>:drcs.vim$ python3 --version
Python 3.7.2
<X_X>:drcs.vim$ pipenv --version
pipenv, version 2018.11.26
```

実行したコマンド類:
===================

```
$ pipenv install ... # 必要なものをインストール
$ pipenv shell
$ python3 main.py
```

Log:
===

```
<X_X>:pirka-ai$ python3 main.py
2019-01-26 22:15:50.789 python3[3688:13254480] warning: service of <NSRemoteView: 0x7f9b73003840> not entitled to set level of host window (to 20)
Traceback (most recent call last):
  File "/Users/Cj-bc/.ghq/github.com/pirka-ai/pirka-ai/gui.py", line 100, in sendButtonClick
    analyzer.main(text, "gui")
  File "/Users/Cj-bc/.ghq/github.com/pirka-ai/pirka-ai/analyzer.py", line 19, in main
    t = MeCab.Tagger("")
  File "/Users/Cj-bc/.local/share/virtualenvs/pirka-ai-WVJLgMHR/lib/python3.7/site-packages/MeCab.py", line 503, in __init__
    this = _MeCab.new_Tagger(*args)
RuntimeError
Abort trap: 6
```

考えられる原因:
===============
いくつかあるのですが
  * 依存パッケージのバージョンの問題
  * Pipenvを使用して使っているのでそれが問題?

なにせpython明るくないのでわからない状態です...
作者さんの環境ではどうなっているでしょうか...?

**Comment by ghost** [comment]
バグの報告、ありがとうございます。僕の環境では正常に動作していますが、正常に動作しない原因が２つあると思われます。
１つめに、GUIモジュール(PyQt5)のデフォルトのフォント色が白になっているため、入力欄の背景色とかぶって文字が表示されていないというものです。これについては、僕の方でpirkaのデフォルトフォントを黒にすることで解決します。
２つめに、形態素解析モジュール(MeCab)が正しくインストールされていないというものです。MeCabをどのようにインストールしたか教えていただけると幸いです。

**Comment by ghost** [comment]
以下の方法でインストールできることがわかりました。macOSの場合は、はじめにHomebrewのインストールをお願いします。（ごめんなさい…）

```console
$ brew install mecab
$ brew install mecab-ipadic
$ brew install swig
```
$ pip install mecab-python3
  (ここでpipのアップデートを求められた場合はアップデートをお願いします。)

**Comment by ghost** [comment]
またわからない点がありましたらご連絡ください！

**Comment by Cj-bc** [comment]
mecabはhomebrew経由、mecab-python3はpipenvで入れました。

インストール方法はこんな感じでした:
```
$ brew install mecab
$ brew install swig
$ pipenv install mecab-python3
```

あ、`mecab-ipadic`だけ入れてなかったです。
入れて試してみますね〜

**Comment by Cj-bc** [comment]
お！！`mecab-ipadic`を入れたところ落ちなくなりました！
そしてフォントの色をいじったら見えるようになりました！！
一応後でPR送っておきますね

**Comment by ghost** [comment]
よかったです！ありがとうございます。
